name: Chatty
version: '${version}'
main: ru.mrbrikster.chatty.Chatty
authors: [ MrBrikster, Kamillaova ]

# This doesn't mean that plugin works only on 1.13+
api-version: '1.13'

softdepend: [ Vault, PlaceholderAPI, Essentials ]
