name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: Chatty
          path: build/libs/chatty.jar
